name = "article-api-cf-test"
compatibility_date = "2025-04-30"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"
account_id = "536934a4c76d71d3c3799cf5582828f9"
